# Jekyll main configuration file
# See https://jekyllrb.com/docs/configuration/ to further customize this file
# Defaults settings https://jekyllrb.com/docs/configuration/#default-configuration

title: 3moji
description: "a home for 3d emoji"

url: https://3moji.org

permalink: date # how your URLs are built, see https://jekyllrb.com/docs/permalinks/#builtinpermalinkstyles

# timezone: America/Los_Angeles # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# theme: minima 
# look for themes on https://github.com/topics/jekyll-theme and https://rubygems.org/search?utf8=%E2%9C%93&query=jekyll-theme

# Files to excludes from your website
# exclude:  
# - .gitignore
# - CNAME 